### ISSUE TITLE
sirupsen/logrus - Case sensitivity issue

### ISSUE THREAD

**Issue by mattevans** [snikch/api#19]
Until recently it was possible to import [Logrus](https://github.com/sirupsen/logrus) in both upper and lower-case formats. This has since changed. See the projects [README](https://github.com/sirupsen/logrus/blob/master/README.md).

Any objections to updating `snikch/api`'s reference to `github.com/Sirupsen/logrus` to `github.com/sirupsen/logrus`?

If you're using glide, there's a workaround (for the meantime) that takes advantage of glides aliasing feature. See [here](https://github.com/sirupsen/logrus/issues/553#issuecomment-306591437).

**Comment by snikch** [comment]
yea go for it.
